# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool: llocal

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'GraduateWork\GraduateWork.csproj'
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: PublishAllureReport@1
  displayName: Publish Report
  condition: always()
  inputs:
    allureVersion: 2.27.0
    testResultsDir: GraduateWork/bin/Debug/net8.0/allure-results
